### ISSUE TITLE
Infografia (Libreria)

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/infografia-de-las-librerias-abicoronel#3]
[LIBRERIA (INFOGRAFIA).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-abicoronel/files/8376801/LIBRERIA.INFOGRAFIA.pdf)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
